@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title Component Diagram voor de backend Adapter architectuur van TripTop systeem

LAYOUT_WITH_LEGEND()


Container(webapp, "TripTop Webapplicatie", "JavaScript, React", "Stelt gebruikers in staat om reizen te plannen en accommodaties te boeken.")

System_Boundary(triptop, "Triptop Systeem") {

    Component(bookingController, "Boeking controller", "Java, Spring", "Behandelt boekings verzoeken van gebruikers.")
    Component(bookingComponent, "Boeking Component", "Java, Spring", "Bevat de bedrijfslogica voor het boeken van reizen.")

    Component(accommodatieBeheer, "Accommodatie Beheer", "Java, Spring", "Verwerkt en beheert accommodatiegegevens.")
    Component(accommodatieRepo, "Accommodatie Repository", "Java, Spring", "Slaat accommodatiedata op.")
    Component(accommodatieAdapter, "Accommodatie Adapter", "Java, Spring", "Adapter voor externe accommodatiebeheerdiensten.")

    Component(bezienswaardighedenBeheer, "Bezienswaardigheden Beheer", "Java, Spring", "Verwerkt en beheert gegevens van toeristische bezienswaardigheden.")
    Component(bezienswaardighedenRepo, "Bezienswaardigheden Repository", "Java, Spring", "Slaat gegevens van bezienswaardigheden op.")
    Component(bezienswaardighedenAdapter, "Bezienswaardigheden Adapter", "Java, Spring", "Adapter voor externe bezienswaardigheden diensten.")
}

ContainerDb(database, "Database", "Postgres", "Slaat gebruikersgegevens, boekingen en betalingen op.")
System_Ext(BookingComAPI, "BookingCom API", "Op halen van accommodaties via Booking.com")
System_Ext(TripAdvisorAPI, "TripAdvisor API", "Voor toeristische informatie en excursies")

Rel(webapp, bookingController, "Verstuurt boekingsverzoeken", "JSON/HTTPS")
Rel(bookingController, bookingComponent, "Verwerkt boekingslogica")


Rel(bookingComponent, accommodatieBeheer, "Behandelt accommodatiegegevens ")
Rel(accommodatieBeheer, accommodatieRepo, "Interactie met database voor accommodatiegegevens")
Rel(accommodatieRepo, database, "Opslag van accommodatiegegevens", "SQL")

Rel(accommodatieBeheer, accommodatieAdapter, "Adapter voor externe accommodatiebeheerdiensten")
Rel(accommodatieAdapter, BookingComAPI, "Ophalen van accommodatie-informatie via Booking.com scraper", "JSON/HTTPS")
Rel(accommodatieAdapter, TripAdvisorAPI, "Ophalen van accommodatie-informatie via Tripadvisor scraper", "JSON/HTTPS")

Rel(bookingComponent, bezienswaardighedenBeheer, "Behandelt bezienswaardigheden gegevens")
Rel(bezienswaardighedenBeheer, bezienswaardighedenRepo, "Interactie met database voor bezienswaardigheden gegevens")
Rel(bezienswaardighedenRepo, database, "Opslag van bezienswaardigheden gegevens", "SQL")

Rel(bezienswaardighedenBeheer, bezienswaardighedenAdapter, "Adapter voor externe bezienswaardigheden diensten")
Rel(bezienswaardighedenAdapter, TripAdvisorAPI, "Ophalen van bezienswaardigheden-informatie via Tripadvisor API", "JSON/HTTPS")
Rel(bezienswaardighedenAdapter, BookingComAPI, "Ophalen van bezienswaardigheden-informatie via BookingCom API", "JSON/HTTPS")
@enduml
