@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

title Dynamisch Container voor het TripTop systeem

Person(user, "Reiziger", "Beheert en wijzigt zijn reis")

System_Boundary(triptop, "Triptop") {

    Container(web, "Triptop Web App", "React (JavaScript / react)", "Biedt gebruikers de mogelijkheid om hun reis te beheren en wijzigingen aan te brengen")

'    Nodig?
'    Container(api, "API Gateway", "Java MVC", "")

    Container(trip_manager, "Reisbeheer API-applicatie", "Java MVC", "Beheert reisoverzicht en wijzigingen van bouwstenen")
}


System_Ext(booking, "Booking API", "Opvragen en beheren van hotelboekingen", "Booking.com, Airbnb")

System_Ext(transport, "Vervoer API", "Houdt vervoersdata bij en signaleert wijzigingen", "NS, KLM, Uber")

System_Ext(attractions, "Bezienswaardigheden API", "Excursies en attracties", "TripAdvisor, Google Places")

System_Ext(horeca, "Horeca API", "Suggesties voor restaurants en cafés", "TheFork, OpenTable")

System_Ext(betaling, "Betalingsservice API", "Betalingen regelen en geld innen", "Stripe")



System_Ext(BookingComAPI, "Bookingcom API", "Reserveren van accommodaties via Booking.com")
System_Ext(AirbnbAPI, "Airbnb API", "Reserveren van accommodaties via Airbnb")

System_Ext(NSAPI, "NS API", "Voor treinroutes en OV informatie binnen Nederland")
System_Ext(KLMAPI, "KLM API", "Voor vluchtinformatie en boekingen")
System_Ext(UberAPI, "Uber API", "Voor lokale taxiritten")

System_Ext(TripAdvisorAPI, "TripAdvisor API", "Voor toeristische informatie en excursies")

System_Ext(TheForkAPI, "TheFork API", "Voor het vinden van restaurants en maken van reserveringen")
System_Ext(OpenTableAPI, "OpenTable API", "Voor reserveren bij cafés en eetgelegenheden")


Rel(user, web, "Gebruiker boekt reis")
Rel(web, trip_manager, "Verzend reisgegevens naar", JSON/HTTPS)
Rel(trip_manager, betaling, "Verzend reisgegevens met betrekking tot boeking naar")
Rel(betaling, trip_manager, "Stuurt *transactie urls door naar")
Rel(trip_manager, web, "Stuurt betalings methode terug")


' Connecting all APIs to Reisbeheer API applicatie
Rel(trip_manager, BookingComAPI, "Opvragen en beheren van hotelboekingen via")
Rel(trip_manager, UberAPI, "Houdt vervoersdata bij en signaleert wijzigingen via")
Rel(trip_manager, KLMAPI, "Houdt vervoersdata bij en signaleert wijzigingen via")
Rel(trip_manager, NSAPI, "Houdt vervoersdata bij en signaleert wijzigingen via")
Rel(trip_manager, TripAdvisorAPI, "Beheren excursies en attracties via")
Rel(trip_manager, TheForkAPI, "Suggesties voor restaurants en cafés via")
Rel(trip_manager, OpenTableAPI, "Suggesties voor restaurants en cafés via")


@enduml