@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
title Systeem Component Diagram voor TripTop

LAYOUT_WITH_LEGEND()

Container(webapp, "'TripTop' Webapplicatie", "JavaScript, React", "Stelt gebruikers in staat om reizen te plannen en accommodaties te boeken.")

System_Boundary(triptop, "TripTop API Applicatie") {

    Component(bookingController, "Boeking Controller", "Java, Spring", "Behandelt boekingsverzoeken van gebruikers.")
    Component(bookingComponent, "Boeking Component", "Java, Spring", "Bevat de bedrijfslogica voor het afhandelen van boekingen.")
    Component(decider, "Decider", "Java, Spring", "Bevat de bedrijfslogica om de state af te handelen")
}


System_Ext(bookingAPI, "Booking API", "Biedt accommodatiegegevens via Bookingcom.")

Rel(bookingAPI, bookingController, "2. Levert accommodatiegegevens", "JSON/HTTPS")
Rel(webapp, bookingController, "1. Verstuurt boekingsverzoeken", "JSON/HTTPS")
Rel(bookingController, decider, "3. Levert accommodatiegegevens", "JSON/HTTPS")
Rel(decider, bookingComponent, "4. Verwerkt boekingslogica")

@enduml